# --- MAPPO specific parameters ---
mode: "adv_policy"
mac: adv_mac

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 32
batch_size_run: 32
batch_size: 32

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 200

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.01
use_rnn: False
standardise_rewards: True
standardise_returns: False
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 4
eps_clip: 0.2
name: "mappo_gma"

iter: 30
alpha: 0.1
eps: 1