# --- MAPPO specific parameters ---

mode: none
mac: basic_mac

action_selector: "soft_policies"
mask_before_softmax: True

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0005

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

t_max: 10050000
test_nepisode: 10
test_interval: 50000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
save_model_interval: 100000

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.01
use_rnn: False
standardise_rewards: True
standardise_returns: False
q_nstep: 5
critic_type: "cv_critic"
epochs: 4
eps_clip: 0.2
name: "mappo"
